language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

before_script:
  - composer install

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
